---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
#這是R Code Chunk
library(rvest) ##第一次使用要先安裝 install.packages("rvest")
library(xml2)
library(XML)
##read_html
a<-"https://www.ptt.cc/bbs/LoL/index.html"
b<-"https://www.ptt.cc/bbs/LoL/index7183.html"
c<-"https://www.ptt.cc/bbs/LoL/index7182.html"
d<-"https://www.ptt.cc/bbs/LoL/index7181.html"
e<-"https://www.ptt.cc/bbs/LoL/index7180.html"
f<-"https://www.ptt.cc/bbs/LoL/index7179.html"

vec<-c(a,b,c,d,e,f)
result<-NULL
for(i in vec)
{
##PTTLOL<-"https://www.ptt.cc/bbs/LoL/index.html"
LOLContent<-read_html(i)
##html_nodes
##html_text
post_title <- LOLContent %>% html_nodes(".title") %>% html_text()
push_num <- LOLContent %>% html_nodes(".nrec") %>% html_text()
post_author <- LOLContent %>% html_nodes(".author") %>% html_text()

testpost_output <- data.frame(testtitle = post_title, testpushnum = push_num, testauthor = post_author)
result<-rbind(result,testpost_output)
next
}
LOL_posts<-result
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(
    LOL_posts[1:100,c("testtitle","testpushnum","testauthor")]) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#Post的類型排名是：
#實況 22個
#問題 17個

#最多推文數的文章是
"[外絮] FW FB" #共62個
#另外有一個推文數很高的文章，但是被刪除了

#最活躍的作者是fdfdfdfd51，共發了4篇文章
```

